/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace WarrantyManager {
      
    export type RepairRecordStruct = {timestamp: BigNumberish, description: string, recordedBy: AddressLike}

    export type RepairRecordStructOutput = [timestamp: bigint, description: string, recordedBy: string] & {timestamp: bigint, description: string, recordedBy: string }
  
    }

  export interface WarrantyManagerInterface extends Interface {
    getFunction(nameOrSignature: "activateWarranty" | "addRepairRecord" | "admin" | "canTransferOwnership" | "changeAdmin" | "checkWarranty" | "getImeiByIndex" | "getRepairHistory" | "getTotalWarranties" | "isAdminAccount" | "isWarrantyOwner" | "markRepairComplete" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminChanged" | "OwnershipTransferred" | "RepairAdded" | "WarrantyActivated" | "WarrantyRenewed"): EventFragment;

    encodeFunctionData(functionFragment: 'activateWarranty', values: [string, string, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'addRepairRecord', values: [string, string]): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'canTransferOwnership', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'changeAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'checkWarranty', values: [string]): string;
encodeFunctionData(functionFragment: 'getImeiByIndex', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRepairHistory', values: [string]): string;
encodeFunctionData(functionFragment: 'getTotalWarranties', values?: undefined): string;
encodeFunctionData(functionFragment: 'isAdminAccount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isWarrantyOwner', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'markRepairComplete', values: [string]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [string, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'activateWarranty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addRepairRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canTransferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'changeAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkWarranty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getImeiByIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRepairHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalWarranties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAdminAccount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isWarrantyOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markRepairComplete', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace AdminChangedEvent {
      export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
      export type OutputTuple = [oldAdmin: string, newAdmin: string];
      export interface OutputObject {oldAdmin: string, newAdmin: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [imei: string, from: AddressLike, to: AddressLike];
      export type OutputTuple = [imei: string, from: string, to: string];
      export interface OutputObject {imei: string, from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RepairAddedEvent {
      export type InputTuple = [imei: string, description: string, timestamp: BigNumberish];
      export type OutputTuple = [imei: string, description: string, timestamp: bigint];
      export interface OutputObject {imei: string, description: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WarrantyActivatedEvent {
      export type InputTuple = [imei: string, owner: AddressLike, expiresAt: BigNumberish];
      export type OutputTuple = [imei: string, owner: string, expiresAt: bigint];
      export interface OutputObject {imei: string, owner: string, expiresAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WarrantyRenewedEvent {
      export type InputTuple = [imei: string, newExpiresAt: BigNumberish];
      export type OutputTuple = [imei: string, newExpiresAt: bigint];
      export interface OutputObject {imei: string, newExpiresAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface WarrantyManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): WarrantyManager;
    waitForDeployment(): Promise<this>;

    interface: WarrantyManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activateWarranty: TypedContractMethod<
      [imei: string, model: string, owner_: AddressLike, durationInDays: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    addRepairRecord: TypedContractMethod<
      [imei: string, description: string, ],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    canTransferOwnership: TypedContractMethod<
      [imei: string, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    changeAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    checkWarranty: TypedContractMethod<
      [imei: string, ],
      [[string, string, bigint, bigint, bigint] & {model: string, owner_: string, activatedAt: bigint, expiresAt: bigint, status: bigint }],
      'view'
    >
    

    
    getImeiByIndex: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getRepairHistory: TypedContractMethod<
      [imei: string, ],
      [WarrantyManager.RepairRecordStructOutput[]],
      'view'
    >
    

    
    getTotalWarranties: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isAdminAccount: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isWarrantyOwner: TypedContractMethod<
      [imei: string, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    markRepairComplete: TypedContractMethod<
      [imei: string, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [imei: string, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activateWarranty'): TypedContractMethod<
      [imei: string, model: string, owner_: AddressLike, durationInDays: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addRepairRecord'): TypedContractMethod<
      [imei: string, description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'canTransferOwnership'): TypedContractMethod<
      [imei: string, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'changeAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkWarranty'): TypedContractMethod<
      [imei: string, ],
      [[string, string, bigint, bigint, bigint] & {model: string, owner_: string, activatedAt: bigint, expiresAt: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getImeiByIndex'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRepairHistory'): TypedContractMethod<
      [imei: string, ],
      [WarrantyManager.RepairRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalWarranties'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isAdminAccount'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isWarrantyOwner'): TypedContractMethod<
      [imei: string, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'markRepairComplete'): TypedContractMethod<
      [imei: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [imei: string, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AdminChanged'): TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RepairAdded'): TypedContractEvent<RepairAddedEvent.InputTuple, RepairAddedEvent.OutputTuple, RepairAddedEvent.OutputObject>;
getEvent(key: 'WarrantyActivated'): TypedContractEvent<WarrantyActivatedEvent.InputTuple, WarrantyActivatedEvent.OutputTuple, WarrantyActivatedEvent.OutputObject>;
getEvent(key: 'WarrantyRenewed'): TypedContractEvent<WarrantyRenewedEvent.InputTuple, WarrantyRenewedEvent.OutputTuple, WarrantyRenewedEvent.OutputObject>;

    filters: {
      
      'AdminChanged(address,address)': TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
      AdminChanged: TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
    

      'OwnershipTransferred(string,address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RepairAdded(string,string,uint256)': TypedContractEvent<RepairAddedEvent.InputTuple, RepairAddedEvent.OutputTuple, RepairAddedEvent.OutputObject>;
      RepairAdded: TypedContractEvent<RepairAddedEvent.InputTuple, RepairAddedEvent.OutputTuple, RepairAddedEvent.OutputObject>;
    

      'WarrantyActivated(string,address,uint256)': TypedContractEvent<WarrantyActivatedEvent.InputTuple, WarrantyActivatedEvent.OutputTuple, WarrantyActivatedEvent.OutputObject>;
      WarrantyActivated: TypedContractEvent<WarrantyActivatedEvent.InputTuple, WarrantyActivatedEvent.OutputTuple, WarrantyActivatedEvent.OutputObject>;
    

      'WarrantyRenewed(string,uint256)': TypedContractEvent<WarrantyRenewedEvent.InputTuple, WarrantyRenewedEvent.OutputTuple, WarrantyRenewedEvent.OutputObject>;
      WarrantyRenewed: TypedContractEvent<WarrantyRenewedEvent.InputTuple, WarrantyRenewedEvent.OutputTuple, WarrantyRenewedEvent.OutputObject>;
    
    };
  }